# Makefile

# Default target to be executed when no arguments are given to make
all: compile run clean

# Compile the Java source file
compile:
	javac Main.java

# Run the compiled Java program
run:
	java Main

# Clean target to remove class files
clean:
	rm -f *.class
